### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sean23189** [Pointifix/AutoDrill#3]
Hello,
I have found a very confusing bug, sometimes when the mod is placing drills it forgets to place bridges, the attached video explains what I mean. There is clearly still enough space to place it just like I did so I'm not quite sure what the reason for this is.

Did I do something wrong inside the settings or is there a different reason that I should look out for?

Attached Video: (I accidentaly clicked the tier 4 drill it doesn't have to do anything with the bug)
https://user-images.githubusercontent.com/66129659/209948806-499486c3-a100-43d6-a340-d329894ebf32.mp4

**Comment by Simon-VIRNECT** [comment]
Hey,

Thanks for the report and for including the video. Yes, that can happen when placing drills on diagonal slim ore patches like you did. The reason for this is that the area of the ores + 1 tile on the outside is simply flood filled with either drills or bridges according to the layout. But if this area is very slim the placed bridges may not be connectable, solving this issue is rather complicated because it requires determining the connected components of the bridges and then adding new bridges between the connected components. For now I can only tell you that sometimes you have to manually fix stuff that the mod builds, it works inany cases, but not in all unfortunately.

**Comment by Pointifix** [comment]
Hey,

Thanks for the report and for including the video. Yes, that can happen when placing drills on diagonal slim ore patches like you did. The reason for this is that the area of the ores + 1 tile on the outside is simply flood filled with either drills or bridges according to the layout. But if this area is very slim the placed bridges may not be connectable, solving this issue is rather complicated because it requires determining the connected components of the bridges and then adding new bridges between the connected components. For now I can only tell you that sometimes you have to manually fix stuff that the mod builds, it works in many cases, but not in all unfortunately.
